const MENU_SEED_DATA = [
  {
    name: 'Margherita Pizza',
    description: 'Classic pizza with fresh mozzarella, tomato sauce, and basil leaves on a thin crust',
    price: 349,
    image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=800&auto=format&fit=crop',
    category: 'Pizza',
  },
  {
    name: 'Pepperoni Pizza',
    description: 'Loaded with spicy pepperoni, mozzarella cheese, and our signature tomato sauce',
    price: 449,
    image: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?w=800&auto=format&fit=crop',
    category: 'Pizza',
  },
  {
    name: 'Classic Cheeseburger',
    description: 'Juicy beef patty with cheddar cheese, lettuce, tomato, and our special sauce',
    price: 249,
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&auto=format&fit=crop',
    category: 'Burger',
  },
  {
    name: 'BBQ Bacon Burger',
    description: 'Smoky BBQ sauce, crispy bacon, onion rings, and melted cheddar on a brioche bun',
    price: 349,
    image: 'https://images.unsplash.com/photo-1553979459-d2229ba7433b?w=800&auto=format&fit=crop',
    category: 'Burger',
  },
  {
    name: 'Spaghetti Carbonara',
    description: 'Traditional Italian pasta with pancetta, egg, parmesan cheese, and black pepper',
    price: 329,
    image: 'https://images.unsplash.com/photo-1612874742237-6526221588e3?w=800&auto=format&fit=crop',
    category: 'Pasta',
  },
  {
    name: 'Penne Arrabbiata',
    description: 'Penne pasta in a spicy tomato sauce with garlic, chili flakes, and fresh parsley',
    price: 279,
    image: 'https://images.unsplash.com/photo-1608219992759-8d74ed8d76eb?w=800&auto=format&fit=crop',
    category: 'Pasta',
  },
  {
    name: 'Caesar Salad',
    description: 'Crisp romaine lettuce, parmesan shavings, croutons, and creamy Caesar dressing',
    price: 229,
    image: 'https://images.unsplash.com/photo-1546793665-c74683f339c1?w=800&auto=format&fit=crop',
    category: 'Salad',
  },
  {
    name: 'Garlic Bread',
    description: 'Toasted artisan bread with garlic butter, herbs, and melted mozzarella cheese',
    price: 129,
    image: 'https://images.unsplash.com/photo-1619531040576-f9416740661e?w=800&auto=format&fit=crop',
    category: 'Appetizer',
  },
  {
    name: 'Tiramisu',
    description: 'Classic Italian dessert with layers of espresso-soaked ladyfingers and mascarpone cream',
    price: 199,
    image: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=800&auto=format&fit=crop',
    category: 'Dessert',
  },
  {
    name: 'Chocolate Lava Cake',
    description: 'Warm chocolate cake with a molten center, served with vanilla ice cream on the side',
    price: 219,
    image: 'https://images.unsplash.com/photo-1624353365286-3f8d62daad51?w=800&auto=format&fit=crop',
    category: 'Dessert',
  },
  {
    name: 'Fresh Lemonade',
    description: 'Freshly squeezed lemonade with a hint of mint and a touch of natural sweetness',
    price: 99,
    image: 'https://images.unsplash.com/photo-1621263764928-df1444c5e859?w=800&auto=format&fit=crop',
    category: 'Beverage',
  },
  {
    name: 'Iced Coffee',
    description: 'Cold brew coffee served over ice with your choice of milk and sweetener options',
    price: 149,
    image: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=800&auto=format&fit=crop',
    category: 'Beverage',
  },
];

module.exports = { MENU_SEED_DATA };
